var searchData=
[
  ['dataflowfact_0',['DataFlowFact',['../structpsr_1_1library__summary_1_1DataFlowFact.html',1,'psr::library_summary']]],
  ['debuglocation_1',['DebugLocation',['../structpsr_1_1DebugLocation.html',1,'psr']]],
  ['defaultaatraits_2',['DefaultAATraits',['../structpsr_1_1DefaultAATraits.html',1,'psr']]],
  ['defaultaatraits_3c_20const_20llvm_3a_3avalue_20_2a_2c_20const_20llvm_3a_3ainstruction_20_2a_20_3e_3',['DefaultAATraits&lt; const llvm::Value *, const llvm::Instruction * &gt;',['../structpsr_1_1DefaultAATraits.html',1,'psr']]],
  ['defaultaliasawareideproblem_4',['DefaultAliasAwareIDEProblem',['../classpsr_1_1DefaultAliasAwareIDEProblem.html',1,'psr']]],
  ['defaultaliasawareifdsproblem_5',['DefaultAliasAwareIFDSProblem',['../classpsr_1_1DefaultAliasAwareIFDSProblem.html',1,'psr']]],
  ['defaultanalysisprinter_6',['DefaultAnalysisPrinter',['../classpsr_1_1DefaultAnalysisPrinter.html',1,'psr']]],
  ['defaultanalysisprinterselector_7',['DefaultAnalysisPrinterSelector',['../structpsr_1_1DefaultAnalysisPrinterSelector.html',1,'psr']]],
  ['defaultanalysisprinterselector_3c_20llvmifdsanalysisdomaindefault_20_3e_8',['DefaultAnalysisPrinterSelector&lt; LLVMIFDSAnalysisDomainDefault &gt;',['../structpsr_1_1DefaultAnalysisPrinterSelector_3_01LLVMIFDSAnalysisDomainDefault_01_4.html',1,'psr']]],
  ['defaultanalysissetup_9',['DefaultAnalysisSetup',['../structpsr_1_1DefaultAnalysisSetup.html',1,'psr']]],
  ['defaultconstruct_10',['DefaultConstruct',['../structpsr_1_1DefaultConstruct.html',1,'psr']]],
  ['defaultdominatortreeanalysis_11',['DefaultDominatorTreeAnalysis',['../classpsr_1_1DefaultDominatorTreeAnalysis.html',1,'psr']]],
  ['defaultedgefunctionsingletoncache_12',['DefaultEdgeFunctionSingletonCache',['../classpsr_1_1DefaultEdgeFunctionSingletonCache.html',1,'psr']]],
  ['defaultedgefunctionsingletoncache_3c_20edgefunctionty_2c_20std_3a_3aenable_5fif_5ft_3c_20edgefunctionbase_3a_3aissoocandidate_3c_20edgefunctionty_20_3e_20_3e_20_3e_13',['DefaultEdgeFunctionSingletonCache&lt; EdgeFunctionTy, std::enable_if_t&lt; EdgeFunctionBase::IsSOOCandidate&lt; EdgeFunctionTy &gt; &gt; &gt;',['../classpsr_1_1DefaultEdgeFunctionSingletonCache_3_01EdgeFunctionTy_00_01std_1_1enable__if__t_3_01Ed99d4575b9952bb290c22403a3c2e2b3.html',1,'psr']]],
  ['defaultedgefunctionsingletoncache_3c_20psr_3a_3aideinstinteractionanalysist_3a_3aiiaaaddlabelsef_20_3e_14',['DefaultEdgeFunctionSingletonCache&lt; psr::IDEInstInteractionAnalysisT::IIAAAddLabelsEF &gt;',['../classpsr_1_1DefaultEdgeFunctionSingletonCache.html',1,'psr']]],
  ['defaultedgefunctionsingletoncache_3c_20psr_3a_3aideinstinteractionanalysist_3a_3aiiaakillorreplaceef_20_3e_15',['DefaultEdgeFunctionSingletonCache&lt; psr::IDEInstInteractionAnalysisT::IIAAKillOrReplaceEF &gt;',['../classpsr_1_1DefaultEdgeFunctionSingletonCache.html',1,'psr']]],
  ['defaultedgefunctionsingletoncacheimpl_16',['DefaultEdgeFunctionSingletonCacheImpl',['../classpsr_1_1DefaultEdgeFunctionSingletonCacheImpl.html',1,'psr']]],
  ['defaultedgefunctionsingletoncacheimpl_3c_20addfactsef_2c_20l_5ft_20_3e_17',['DefaultEdgeFunctionSingletonCacheImpl&lt; AddFactsEF, l_t &gt;',['../classpsr_1_1DefaultEdgeFunctionSingletonCacheImpl.html',1,'psr']]],
  ['defaultedgefunctionsingletoncacheimpl_3c_20edgefunctionty_2c_20edgefunctionty_3a_3al_5ft_20_3e_18',['DefaultEdgeFunctionSingletonCacheImpl&lt; EdgeFunctionTy, EdgeFunctionTy::l_t &gt;',['../classpsr_1_1DefaultEdgeFunctionSingletonCacheImpl.html',1,'psr']]],
  ['defaultedgefunctionsingletoncacheimpl_3c_20generateef_2c_20l_5ft_20_3e_19',['DefaultEdgeFunctionSingletonCacheImpl&lt; GenerateEF, l_t &gt;',['../classpsr_1_1DefaultEdgeFunctionSingletonCacheImpl.html',1,'psr']]],
  ['defaultedgefunctionsingletoncacheimpl_3c_20psr_3a_3aideinstinteractionanalysist_3a_3aiiaaaddlabelsef_2c_20edgefunctionty_3a_3al_5ft_20_3e_20',['DefaultEdgeFunctionSingletonCacheImpl&lt; psr::IDEInstInteractionAnalysisT::IIAAAddLabelsEF, EdgeFunctionTy::l_t &gt;',['../classpsr_1_1DefaultEdgeFunctionSingletonCacheImpl.html',1,'psr']]],
  ['defaultedgefunctionsingletoncacheimpl_3c_20psr_3a_3aideinstinteractionanalysist_3a_3aiiaakillorreplaceef_2c_20edgefunctionty_3a_3al_5ft_20_3e_21',['DefaultEdgeFunctionSingletonCacheImpl&lt; psr::IDEInstInteractionAnalysisT::IIAAKillOrReplaceEF, EdgeFunctionTy::l_t &gt;',['../classpsr_1_1DefaultEdgeFunctionSingletonCacheImpl.html',1,'psr']]],
  ['defaultidesolverconfig_22',['DefaultIDESolverConfig',['../structpsr_1_1DefaultIDESolverConfig.html',1,'psr']]],
  ['defaultidesolverconfig_3c_20problemty_2c_20std_3a_3aenable_5fif_5ft_3c_20std_3a_3ais_5fbase_5fof_5fv_3c_20ifdstabulationproblem_3c_20typename_20problemty_3a_3aproblemanalysisdomain_20_3e_2c_20problemty_20_3e_20_3e_20_3e_23',['DefaultIDESolverConfig&lt; ProblemTy, std::enable_if_t&lt; std::is_base_of_v&lt; IFDSTabulationProblem&lt; typename ProblemTy::ProblemAnalysisDomain &gt;, ProblemTy &gt; &gt; &gt;',['../structpsr_1_1DefaultIDESolverConfig_3_01ProblemTy_00_01std_1_1enable__if__t_3_01std_1_1is__base_adc4e44d50d6a7f0c5ce731aba6dd5ad.html',1,'psr']]],
  ['defaultllvmanalysisprinter_24',['DefaultLLVMAnalysisPrinter',['../classpsr_1_1DefaultLLVMAnalysisPrinter.html',1,'psr']]],
  ['defaultmapkeycompressor_25',['DefaultMapKeyCompressor',['../classpsr_1_1DefaultMapKeyCompressor.html',1,'psr']]],
  ['defaultnoaliasideproblem_26',['DefaultNoAliasIDEProblem',['../classpsr_1_1DefaultNoAliasIDEProblem.html',1,'psr']]],
  ['defaultnoaliasifdsproblem_27',['DefaultNoAliasIFDSProblem',['../classpsr_1_1DefaultNoAliasIFDSProblem.html',1,'psr']]],
  ['defaultnodetransform_28',['DefaultNodeTransform',['../structpsr_1_1DefaultNodeTransform.html',1,'psr']]],
  ['defaultreachableallocationsitesideproblem_29',['DefaultReachableAllocationSitesIDEProblem',['../classpsr_1_1DefaultReachableAllocationSitesIDEProblem.html',1,'psr']]],
  ['defaultreachableallocationsitesifdsproblem_30',['DefaultReachableAllocationSitesIFDSProblem',['../classpsr_1_1DefaultReachableAllocationSitesIFDSProblem.html',1,'psr']]],
  ['demanddrivenanalysis_31',['DemandDrivenAnalysis',['../classpsr_1_1DemandDrivenAnalysis.html',1,'psr']]],
  ['densemapinfo_3c_20psr_3a_3aboxedconstptr_3c_20c_20_3e_20_3e_32',['DenseMapInfo&lt; psr::BoxedConstPtr&lt; C &gt; &gt;',['../structllvm_1_1DenseMapInfo_3_01psr_1_1BoxedConstPtr_3_01C_01_4_01_4.html',1,'llvm']]],
  ['densemapinfo_3c_20psr_3a_3aboxedptr_3c_20c_20_3e_20_3e_33',['DenseMapInfo&lt; psr::BoxedPtr&lt; C &gt; &gt;',['../structllvm_1_1DenseMapInfo_3_01psr_1_1BoxedPtr_3_01C_01_4_01_4.html',1,'llvm']]],
  ['densemapinfo_3c_20psr_3a_3adummypair_3c_20t_20_3e_20_3e_34',['DenseMapInfo&lt; psr::DummyPair&lt; T &gt; &gt;',['../structllvm_1_1DenseMapInfo_3_01psr_1_1DummyPair_3_01T_01_4_01_4.html',1,'llvm']]],
  ['densemapinfo_3c_20psr_3a_3aedgefunction_3c_20l_20_3e_20_3e_35',['DenseMapInfo&lt; psr::EdgeFunction&lt; L &gt; &gt;',['../structllvm_1_1DenseMapInfo_3_01psr_1_1EdgeFunction_3_01L_01_4_01_4.html',1,'llvm']]],
  ['densemapinfo_3c_20psr_3a_3aideiiaflowfact_20_3e_36',['DenseMapInfo&lt; psr::IDEIIAFlowFact &gt;',['../structllvm_1_1DenseMapInfo_3_01psr_1_1IDEIIAFlowFact_01_4.html',1,'llvm']]],
  ['denseset_37',['DenseSet',['../classpsr_1_1DenseSet.html',1,'psr']]],
  ['denseset_3c_20interpropagationjobref_2c_20interpropagationjobrefdsi_20_3e_38',['DenseSet&lt; InterPropagationJobRef, InterPropagationJobRefDSI &gt;',['../classpsr_1_1DenseSet.html',1,'psr']]],
  ['denseset_3c_20uint32_5ft_20_3e_39',['DenseSet&lt; uint32_t &gt;',['../classpsr_1_1DenseSet.html',1,'psr']]],
  ['denseset_3c_20uint64_5ft_20_3e_40',['DenseSet&lt; uint64_t &gt;',['../classpsr_1_1DenseSet.html',1,'psr']]],
  ['densetable1d_41',['DenseTable1d',['../classpsr_1_1DenseTable1d.html',1,'psr']]],
  ['densetable1d_3c_20k_2c_20emptytype_20_3e_42',['DenseTable1d&lt; K, EmptyType &gt;',['../classpsr_1_1DenseTable1d_3_01K_00_01EmptyType_01_4.html',1,'psr']]],
  ['densetable1d_3c_20std_3a_3apair_3c_20uint64_5ft_2c_20uint64_5ft_20_3e_2c_20ctr_5fff_5ft_20_3e_43',['DenseTable1d&lt; std::pair&lt; uint64_t, uint64_t &gt;, ctr_ff_t &gt;',['../classpsr_1_1DenseTable1d.html',1,'psr']]],
  ['densetable1d_3c_20uint64_5ft_2c_20call_5fff_5ft_20_3e_44',['DenseTable1d&lt; uint64_t, call_ff_t &gt;',['../classpsr_1_1DenseTable1d.html',1,'psr']]],
  ['densetable1d_3c_20uint64_5ft_2c_20const_20interpropagationjob_20_2a_20_3e_45',['DenseTable1d&lt; uint64_t, const InterPropagationJob * &gt;',['../classpsr_1_1DenseTable1d.html',1,'psr']]],
  ['densetable1d_3c_20uint64_5ft_2c_20ctr_5fff_5ft_20_3e_46',['DenseTable1d&lt; uint64_t, ctr_ff_t &gt;',['../classpsr_1_1DenseTable1d.html',1,'psr']]],
  ['densetable1d_3c_20uint64_5ft_2c_20summary_5fff_5ft_20_3e_47',['DenseTable1d&lt; uint64_t, summary_ff_t &gt;',['../classpsr_1_1DenseTable1d.html',1,'psr']]],
  ['dequeworklist_48',['DequeWorkList',['../classpsr_1_1DequeWorkList.html',1,'psr']]],
  ['dibasedtypehierarchy_49',['DIBasedTypeHierarchy',['../classpsr_1_1DIBasedTypeHierarchy.html',1,'psr']]],
  ['dibasedtypehierarchydata_50',['DIBasedTypeHierarchyData',['../structpsr_1_1DIBasedTypeHierarchyData.html',1,'psr']]],
  ['dotconfig_51',['DOTConfig',['../classpsr_1_1DOTConfig.html',1,'psr']]],
  ['dotedge_52',['DOTEdge',['../structpsr_1_1DOTEdge.html',1,'psr']]],
  ['dotfactsubgraph_53',['DOTFactSubGraph',['../structpsr_1_1DOTFactSubGraph.html',1,'psr']]],
  ['dotfunctionsubgraph_54',['DOTFunctionSubGraph',['../structpsr_1_1DOTFunctionSubGraph.html',1,'psr']]],
  ['dotgraph_55',['DOTGraph',['../structpsr_1_1DOTGraph.html',1,'psr']]],
  ['dotnode_56',['DOTNode',['../structpsr_1_1DOTNode.html',1,'psr']]],
  ['dummydensetable1d_57',['DummyDenseTable1d',['../classpsr_1_1DummyDenseTable1d.html',1,'psr']]],
  ['dummypair_58',['DummyPair',['../structpsr_1_1DummyPair.html',1,'psr']]],
  ['dummypair_3c_20k_20_3e_59',['DummyPair&lt; K &gt;',['../structpsr_1_1DummyPair.html',1,'psr']]],
  ['dummyunorderedtable1d_60',['DummyUnorderedTable1d',['../classpsr_1_1DummyUnorderedTable1d.html',1,'psr']]]
];
