var searchData=
[
  ['dataflowfact_0',['DataFlowFact',['../structpsr_1_1library__summary_1_1DataFlowFact.html',1,'psr::library_summary']]],
  ['debuglocation_1',['DebugLocation',['../structpsr_1_1DebugLocation.html',1,'psr']]],
  ['defaultaatraits_2',['DefaultAATraits',['../structpsr_1_1DefaultAATraits.html',1,'psr']]],
  ['defaultaatraits_3c_20const_20llvm_3a_3avalue_20_2a_2c_20const_20llvm_3a_3ainstruction_20_2a_20_3e_3',['DefaultAATraits&lt; const llvm::Value *, const llvm::Instruction * &gt;',['../structpsr_1_1DefaultAATraits.html',1,'psr']]],
  ['defaultaliasawareideproblem_4',['DefaultAliasAwareIDEProblem',['../classpsr_1_1DefaultAliasAwareIDEProblem.html',1,'psr']]],
  ['defaultaliasawareifdsproblem_5',['DefaultAliasAwareIFDSProblem',['../classpsr_1_1DefaultAliasAwareIFDSProblem.html',1,'psr']]],
  ['defaultallocsitesawareideproblem_6',['DefaultAllocSitesAwareIDEProblem',['../classpsr_1_1DefaultAllocSitesAwareIDEProblem.html',1,'psr']]],
  ['defaultallocsitesawareifdsproblem_7',['DefaultAllocSitesAwareIFDSProblem',['../classpsr_1_1DefaultAllocSitesAwareIFDSProblem.html',1,'psr']]],
  ['defaultanalysisprinter_8',['DefaultAnalysisPrinter',['../classpsr_1_1DefaultAnalysisPrinter.html',1,'psr']]],
  ['defaultanalysisprinterselector_9',['DefaultAnalysisPrinterSelector',['../structpsr_1_1DefaultAnalysisPrinterSelector.html',1,'psr']]],
  ['defaultanalysisprinterselector_3c_20llvmifdsanalysisdomaindefault_20_3e_10',['DefaultAnalysisPrinterSelector&lt; LLVMIFDSAnalysisDomainDefault &gt;',['../structpsr_1_1DefaultAnalysisPrinterSelector_3_01LLVMIFDSAnalysisDomainDefault_01_4.html',1,'psr']]],
  ['defaultanalysissetup_11',['DefaultAnalysisSetup',['../structpsr_1_1DefaultAnalysisSetup.html',1,'psr']]],
  ['defaultconstruct_12',['DefaultConstruct',['../structpsr_1_1DefaultConstruct.html',1,'psr']]],
  ['defaultdocastifpossible_13',['DefaultDoCastIfPossible',['../classDefaultDoCastIfPossible.html',1,'']]],
  ['defaultdominatortreeanalysis_14',['DefaultDominatorTreeAnalysis',['../classpsr_1_1DefaultDominatorTreeAnalysis.html',1,'psr']]],
  ['defaultedgefunctionsingletoncache_15',['DefaultEdgeFunctionSingletonCache',['../classpsr_1_1DefaultEdgeFunctionSingletonCache.html',1,'psr']]],
  ['defaultedgefunctionsingletoncache_3c_20edgefunctionty_20_3e_16',['DefaultEdgeFunctionSingletonCache&lt; EdgeFunctionTy &gt;',['../classpsr_1_1DefaultEdgeFunctionSingletonCache_3_01EdgeFunctionTy_01_4.html',1,'psr']]],
  ['defaultedgefunctionsingletoncache_3c_20psr_3a_3aideinstinteractionanalysist_3a_3aiiaaaddlabelsef_20_3e_17',['DefaultEdgeFunctionSingletonCache&lt; psr::IDEInstInteractionAnalysisT::IIAAAddLabelsEF &gt;',['../classpsr_1_1DefaultEdgeFunctionSingletonCache.html',1,'psr']]],
  ['defaultedgefunctionsingletoncache_3c_20psr_3a_3aideinstinteractionanalysist_3a_3aiiaakillorreplaceef_20_3e_18',['DefaultEdgeFunctionSingletonCache&lt; psr::IDEInstInteractionAnalysisT::IIAAKillOrReplaceEF &gt;',['../classpsr_1_1DefaultEdgeFunctionSingletonCache.html',1,'psr']]],
  ['defaultedgefunctionsingletoncacheimpl_19',['DefaultEdgeFunctionSingletonCacheImpl',['../classpsr_1_1DefaultEdgeFunctionSingletonCacheImpl.html',1,'psr']]],
  ['defaultedgefunctionsingletoncacheimpl_3c_20addfactsef_2c_20l_5ft_20_3e_20',['DefaultEdgeFunctionSingletonCacheImpl&lt; AddFactsEF, l_t &gt;',['../classpsr_1_1DefaultEdgeFunctionSingletonCacheImpl.html',1,'psr']]],
  ['defaultedgefunctionsingletoncacheimpl_3c_20edgefunctionty_2c_20edgefunctionty_3a_3al_5ft_20_3e_21',['DefaultEdgeFunctionSingletonCacheImpl&lt; EdgeFunctionTy, EdgeFunctionTy::l_t &gt;',['../classpsr_1_1DefaultEdgeFunctionSingletonCacheImpl.html',1,'psr']]],
  ['defaultedgefunctionsingletoncacheimpl_3c_20generateef_2c_20l_5ft_20_3e_22',['DefaultEdgeFunctionSingletonCacheImpl&lt; GenerateEF, l_t &gt;',['../classpsr_1_1DefaultEdgeFunctionSingletonCacheImpl.html',1,'psr']]],
  ['defaultedgefunctionsingletoncacheimpl_3c_20psr_3a_3aideinstinteractionanalysist_3a_3aiiaaaddlabelsef_2c_20edgefunctionty_3a_3al_5ft_20_3e_23',['DefaultEdgeFunctionSingletonCacheImpl&lt; psr::IDEInstInteractionAnalysisT::IIAAAddLabelsEF, EdgeFunctionTy::l_t &gt;',['../classpsr_1_1DefaultEdgeFunctionSingletonCacheImpl.html',1,'psr']]],
  ['defaultedgefunctionsingletoncacheimpl_3c_20psr_3a_3aideinstinteractionanalysist_3a_3aiiaakillorreplaceef_2c_20edgefunctionty_3a_3al_5ft_20_3e_24',['DefaultEdgeFunctionSingletonCacheImpl&lt; psr::IDEInstInteractionAnalysisT::IIAAKillOrReplaceEF, EdgeFunctionTy::l_t &gt;',['../classpsr_1_1DefaultEdgeFunctionSingletonCacheImpl.html',1,'psr']]],
  ['defaultidesolverconfig_25',['DefaultIDESolverConfig',['../structpsr_1_1DefaultIDESolverConfig.html',1,'psr']]],
  ['defaultidesolverconfig_3c_20problemty_20_3e_26',['DefaultIDESolverConfig&lt; ProblemTy &gt;',['../structpsr_1_1DefaultIDESolverConfig_3_01ProblemTy_01_4.html',1,'psr']]],
  ['defaultllvmanalysisprinter_27',['DefaultLLVMAnalysisPrinter',['../classpsr_1_1DefaultLLVMAnalysisPrinter.html',1,'psr']]],
  ['defaultmapkeycompressor_28',['DefaultMapKeyCompressor',['../classpsr_1_1DefaultMapKeyCompressor.html',1,'psr']]],
  ['defaultnoaliasideproblem_29',['DefaultNoAliasIDEProblem',['../classpsr_1_1DefaultNoAliasIDEProblem.html',1,'psr']]],
  ['defaultnoaliasifdsproblem_30',['DefaultNoAliasIFDSProblem',['../classpsr_1_1DefaultNoAliasIFDSProblem.html',1,'psr']]],
  ['defaultnodetransform_31',['DefaultNodeTransform',['../structpsr_1_1DefaultNodeTransform.html',1,'psr']]],
  ['defaultreachableallocationsitesideproblem_32',['DefaultReachableAllocationSitesIDEProblem',['../classpsr_1_1DefaultReachableAllocationSitesIDEProblem.html',1,'psr']]],
  ['defaultreachableallocationsitesifdsproblem_33',['DefaultReachableAllocationSitesIFDSProblem',['../classpsr_1_1DefaultReachableAllocationSitesIFDSProblem.html',1,'psr']]],
  ['defaultreachablefunctions_34',['DefaultReachableFunctions',['../structpsr_1_1VTAResolver_1_1DefaultReachableFunctions.html',1,'psr::VTAResolver']]],
  ['demanddrivenanalysis_35',['DemandDrivenAnalysis',['../classpsr_1_1DemandDrivenAnalysis.html',1,'psr']]],
  ['densemapinfo_3c_20psr_3a_3aboxedconstptr_3c_20c_20_3e_20_3e_36',['DenseMapInfo&lt; psr::BoxedConstPtr&lt; C &gt; &gt;',['../structllvm_1_1DenseMapInfo_3_01psr_1_1BoxedConstPtr_3_01C_01_4_01_4.html',1,'llvm']]],
  ['densemapinfo_3c_20psr_3a_3aboxedptr_3c_20c_20_3e_20_3e_37',['DenseMapInfo&lt; psr::BoxedPtr&lt; C &gt; &gt;',['../structllvm_1_1DenseMapInfo_3_01psr_1_1BoxedPtr_3_01C_01_4_01_4.html',1,'llvm']]],
  ['densemapinfo_3c_20psr_3a_3acfl_5ffieldsens_3a_3afieldstringnode_20_3e_38',['DenseMapInfo&lt; psr::cfl_fieldsens::FieldStringNode &gt;',['../structllvm_1_1DenseMapInfo_3_01psr_1_1cfl__fieldsens_1_1FieldStringNode_01_4.html',1,'llvm']]],
  ['densemapinfo_3c_20psr_3a_3adummypair_3c_20t_20_3e_20_3e_39',['DenseMapInfo&lt; psr::DummyPair&lt; T &gt; &gt;',['../structllvm_1_1DenseMapInfo_3_01psr_1_1DummyPair_3_01T_01_4_01_4.html',1,'llvm']]],
  ['densemapinfo_3c_20psr_3a_3aedgefunction_3c_20l_20_3e_20_3e_40',['DenseMapInfo&lt; psr::EdgeFunction&lt; L &gt; &gt;',['../structllvm_1_1DenseMapInfo_3_01psr_1_1EdgeFunction_3_01L_01_4_01_4.html',1,'llvm']]],
  ['densemapinfo_3c_20psr_3a_3aideiiaflowfact_20_3e_41',['DenseMapInfo&lt; psr::IDEIIAFlowFact &gt;',['../structllvm_1_1DenseMapInfo_3_01psr_1_1IDEIIAFlowFact_01_4.html',1,'llvm']]],
  ['densemapinfo_3c_20psr_3a_3asccid_3c_20graphnodeid_20_3e_20_3e_42',['DenseMapInfo&lt; psr::SCCId&lt; GraphNodeId &gt; &gt;',['../structllvm_1_1DenseMapInfo_3_01psr_1_1SCCId_3_01GraphNodeId_01_4_01_4.html',1,'llvm']]],
  ['densemapinfo_3c_20psr_3a_3avta_3a_3atagnode_20_3e_43',['DenseMapInfo&lt; psr::vta::TAGNode &gt;',['../structllvm_1_1DenseMapInfo_3_01psr_1_1vta_1_1TAGNode_01_4.html',1,'llvm']]],
  ['densemapinfo_3c_20psr_3a_3avta_3a_3atagnodeid_20_3e_44',['DenseMapInfo&lt; psr::vta::TAGNodeId &gt;',['../structllvm_1_1DenseMapInfo_3_01psr_1_1vta_1_1TAGNodeId_01_4.html',1,'llvm']]],
  ['denseset_45',['DenseSet',['../classpsr_1_1DenseSet.html',1,'psr']]],
  ['denseset_3c_20interpropagationjobref_2c_20interpropagationjobrefdsi_20_3e_46',['DenseSet&lt; InterPropagationJobRef, InterPropagationJobRefDSI &gt;',['../classpsr_1_1DenseSet.html',1,'psr']]],
  ['denseset_3c_20uint32_5ft_20_3e_47',['DenseSet&lt; uint32_t &gt;',['../classpsr_1_1DenseSet.html',1,'psr']]],
  ['denseset_3c_20uint64_5ft_20_3e_48',['DenseSet&lt; uint64_t &gt;',['../classpsr_1_1DenseSet.html',1,'psr']]],
  ['densetable1d_49',['DenseTable1d',['../classpsr_1_1DenseTable1d.html',1,'psr']]],
  ['densetable1d_3c_20k_2c_20emptytype_20_3e_50',['DenseTable1d&lt; K, EmptyType &gt;',['../classpsr_1_1DenseTable1d_3_01K_00_01EmptyType_01_4.html',1,'psr']]],
  ['densetable1d_3c_20std_3a_3apair_3c_20uint64_5ft_2c_20uint64_5ft_20_3e_2c_20ctr_5fff_5ft_20_3e_51',['DenseTable1d&lt; std::pair&lt; uint64_t, uint64_t &gt;, ctr_ff_t &gt;',['../classpsr_1_1DenseTable1d.html',1,'psr']]],
  ['densetable1d_3c_20uint64_5ft_2c_20call_5fff_5ft_20_3e_52',['DenseTable1d&lt; uint64_t, call_ff_t &gt;',['../classpsr_1_1DenseTable1d.html',1,'psr']]],
  ['densetable1d_3c_20uint64_5ft_2c_20const_20interpropagationjob_20_2a_20_3e_53',['DenseTable1d&lt; uint64_t, const InterPropagationJob * &gt;',['../classpsr_1_1DenseTable1d.html',1,'psr']]],
  ['densetable1d_3c_20uint64_5ft_2c_20ctr_5fff_5ft_20_3e_54',['DenseTable1d&lt; uint64_t, ctr_ff_t &gt;',['../classpsr_1_1DenseTable1d.html',1,'psr']]],
  ['densetable1d_3c_20uint64_5ft_2c_20summary_5fff_5ft_20_3e_55',['DenseTable1d&lt; uint64_t, summary_ff_t &gt;',['../classpsr_1_1DenseTable1d.html',1,'psr']]],
  ['dequeworklist_56',['DequeWorkList',['../classpsr_1_1DequeWorkList.html',1,'psr']]],
  ['dibasedtypehierarchy_57',['DIBasedTypeHierarchy',['../classpsr_1_1DIBasedTypeHierarchy.html',1,'psr']]],
  ['dibasedtypehierarchydata_58',['DIBasedTypeHierarchyData',['../structpsr_1_1DIBasedTypeHierarchyData.html',1,'psr']]],
  ['dotconfig_59',['DOTConfig',['../classpsr_1_1DOTConfig.html',1,'psr']]],
  ['dotedge_60',['DOTEdge',['../structpsr_1_1DOTEdge.html',1,'psr']]],
  ['dotfactsubgraph_61',['DOTFactSubGraph',['../structpsr_1_1DOTFactSubGraph.html',1,'psr']]],
  ['dotfunctionsubgraph_62',['DOTFunctionSubGraph',['../structpsr_1_1DOTFunctionSubGraph.html',1,'psr']]],
  ['dotgraph_63',['DOTGraph',['../structpsr_1_1DOTGraph.html',1,'psr']]],
  ['dotnode_64',['DOTNode',['../structpsr_1_1DOTNode.html',1,'psr']]],
  ['dummydensetable1d_65',['DummyDenseTable1d',['../classpsr_1_1DummyDenseTable1d.html',1,'psr']]],
  ['dummypair_66',['DummyPair',['../structpsr_1_1DummyPair.html',1,'psr']]],
  ['dummypair_3c_20k_20_3e_67',['DummyPair&lt; K &gt;',['../structpsr_1_1DummyPair.html',1,'psr']]],
  ['dummyunorderedtable1d_68',['DummyUnorderedTable1d',['../classpsr_1_1DummyUnorderedTable1d.html',1,'psr']]]
];
