FROM ubuntu:22.04


RUN apt -y update && apt -y upgrade && apt install bash  -y
RUN DEBIAN_FRONTEND=noninteractive apt -y install wget gpg software-properties-common lsb-release git make python3 python3-pip -y
RUN apt -y update && apt -y install cmake ninja-build sudo


RUN set -exu; \
    useradd -p test -s /bin/bash -m vscode; \
    groupadd docker; \
    usermod -aG docker vscode; \
    usermod -aG sudo vscode;

USER vscode
