/******************************************************************************
 * Copyright (c) 2026 Fabian Schiebel.
 * All rights reserved. This program and the accompanying materials are made
 * available under the terms of LICENSE.txt.
 *
 * Contributors:
 *     Fabian Schiebel and others
 *****************************************************************************/

#ifndef PHASAR_PHASARLLVM_CONTROLFLOW_EXTERNCALLBACKMODEL_H
#define PHASAR_PHASARLLVM_CONTROLFLOW_EXTERNCALLBACKMODEL_H

#include "llvm/ADT/StringRef.h"
#include "llvm/IR/Function.h"

namespace psr {
class LLVMProjectIRDB;

/// \brief Provides utilities to model calls through known external callback
/// brokers.
///
/// The inserted model keeps the original broker call and adds a regular call to
/// the callback argument, so later analyses still see an ordinary call-site.
class ExternCallbackModel {
public:
  static constexpr llvm::StringLiteral ModelPrefix = "__psrExternCallbackModel";

  /// Rewrites all supported external callback call-sites in \p IRDB.
  ///
  /// \returns the number of rewritten call-sites.
  static size_t rewriteCalls(LLVMProjectIRDB &IRDB);

  /// Returns true, if a function was generated by the ExternCallbackModel.
  [[nodiscard]] static bool isPhasarGenerated(const llvm::Function &F) noexcept;
};
} // namespace psr

#endif // PHASAR_PHASARLLVM_CONTROLFLOW_EXTERNCALLBACKMODEL_H
