/******************************************************************************
 * Copyright (c) 2024 Fabian Schiebel.
 * All rights reserved. This program and the accompanying materials are made
 * available under the terms of LICENSE.txt.
 *
 * Contributors:
 *     Fabian Schiebel and others
 *****************************************************************************/

#ifndef PHASAR_PHASARLLVM_CONTROLFLOW_GLOBALCTORSDTORSMODEL_H
#define PHASAR_PHASARLLVM_CONTROLFLOW_GLOBALCTORSDTORSMODEL_H

#include "llvm/ADT/ArrayRef.h"
#include "llvm/IR/Function.h"

namespace psr {
class LLVMProjectIRDB;

class GlobalCtorsDtorsModel {
public:
  static constexpr llvm::StringLiteral ModelName =
      "__psrCRuntimeGlobalCtorsModel";

  static constexpr llvm::StringLiteral DtorModelName =
      "__psrCRuntimeGlobalDtorsModel";

  static constexpr llvm::StringLiteral DtorsCallerName =
      "__psrGlobalDtorsCaller";

  static constexpr llvm::StringLiteral UserEntrySelectorName =
      "__psrCRuntimeUserEntrySelector";

  /// @brief
  /// Function that creates a new global model and inserts it into the IRDB. The
  /// returned function is the global model that was inserted.
  /// @param[in, out] IRDB Intermediate representation data base that will have
  /// the global model inserted.
  /// @param[in] UserEntryPoints Entry points for the program given as
  /// llvm::Function pointers.
  static llvm::Function *
  buildModel(LLVMProjectIRDB &IRDB,
             llvm::ArrayRef<llvm::Function *> UserEntryPoints);
  /// @brief
  /// Function that creates a new global model and inserts it into the IRDB. The
  /// returned function is the global model that was inserted.
  /// @param[in, out] IRDB Intermediate representation data base that will have
  /// the global model inserted.
  /// @param[in] UserEntryPoints Entry points for the program given as
  /// std::strings.
  static llvm::Function *
  buildModel(LLVMProjectIRDB &IRDB,
             llvm::ArrayRef<std::string> UserEntryPoints);

  /// Returns true, if a function was generated by phasar.
  [[nodiscard]] static bool isPhasarGenerated(const llvm::Function &F) noexcept;
};
} // namespace psr

#endif // PHASAR_PHASARLLVM_CONTROLFLOW_GLOBALCTORSDTORSMODEL_H
